### ISSUE TITLE
Factory Method Identification

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1292]
I am writing a reflective tool that constructs RAML from a different storage format. I need to know which features are constructed using which methods. The test below shows the effect. I can create an array and call the setter, but on generation 

* **I'm submitting a ...**
  - [x] question

* **What is the current behavior?**

On some features, setting an array of items succeeds, on some, the validation and generation fails with a stack trace and no explanation. For example `api.endPoint` vs `api.documentation`.

A delayed runtime exception is thrown on validation and generation.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

See testCase below, showing behaviour for `endPoint`.

* **What is the expected behavior?**

Semantic exception thrown on method call.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

Cannot construct software for my client. Cannot use AMF tooling.

* **Please tell us about your environment:**
  
  - AMF Version: 4
  - AMF Distribution: JVM
  - Operating System: Ubuntu Linux
  - Link to your project: commercial

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)
```java
import static java.util.Arrays.asList;
import static webapi.Raml10.validate;

import java.util.Arrays;
import java.util.Collections;
import java.util.concurrent.ExecutionException;

import org.junit.jupiter.api.Test;

import amf.client.model.domain.EndPoint;
import amf.client.model.domain.WebApi;
import amf.client.validate.ValidationReport;
import webapi.WebApiDocument;
import webapi.WebApiParser;

class EndPointCreationFailsTest {

	@Test
	void test() throws InterruptedException, ExecutionException {
		// Init WebApiParser to set up necessary plugins
		WebApiParser.init().get();

		// Create API instance with title, description, protocols, mediaType,
		// 'accepts' list and version
		final WebApi api = new WebApi().withName("Foo org API").withDescription("Describes Foo org API")
				.withSchemes(Arrays.asList("http", "https"))
				.withContentType(Collections.singletonList("application/json"))
				.withAccepts(Collections.singletonList("application/json")).withVersion("1.1");

		// Set baseUrl
		api.withServer("https://api.spotify.com/v/{version}");

		// Create endpoint with path /users, title and description
		final EndPoint endPoint = new EndPoint();
		endPoint.withId("/users");
		endPoint.withName("Users endpoint");
		endPoint.withDescription("Lists users");

		api.withEndPoints(asList(endPoint));

		WebApiDocument model = new WebApiDocument();
		model.withEncodes(api);

		ValidationReport validationReport = validate(model).get();

	}

}

```

**Comment by tomsfernandez** [comment]
Hi @jgsuess!. Three questions:
- What AMF version specifically are you using ?
- How it the `validate` method implemented ?
- What is the exception this throws ?

**Comment by jgsuess** [comment]
`validate` is an API method provided by the product: `import static webapi.Raml10.validate;`
AMF: `2.12_4`

```
amf-aml_2.12-4.1.19.jar
amf-core_2.12-4.1.20.jar
amf-validation_2.12-4.0.3.jar
amf-webapi_2.12-4.0.3.jar
antlr4-runtime-4.5.3.jar
collection-0.7.jar
commons-beanutils-1.9.3.jar
commons-cli-1.4.jar
commons-codec-1.11.jar
commons-collections-3.2.2.jar
commons-compress-1.19.jar
commons-csv-1.5.jar
commons-digester-1.8.1.jar
commons-io-2.6.jar
commons-lang3-3.4.jar
commons-logging-1.2.jar
commons-validator-1.6.jar
handy-uri-templates-2.1.6.jar
httpclient-4.5.5.jar
httpclient-cache-4.5.5.jar
httpcore-4.4.9.jar
jackson-annotations-2.9.0.jar
jackson-core-2.9.8.jar
jackson-databind-2.9.8.jar
jcl-over-slf4j-1.7.26.jar
jena-arq-3.11.0.jar
jena-base-3.11.0.jar
jena-core-3.11.0.jar
jena-iri-3.11.0.jar
jena-shaded-guava-3.11.0.jar
joda-time-2.9.4.jar
json-20180130.jar
json4s-ast_2.12-3.5.4.jar
json4s-core_2.12-3.5.4.jar
json4s-native_2.12-3.5.4.jar
json4s-scalap_2.12-3.5.4.jar
jsonld-java-0.12.3.jar
libthrift-0.12.0.jar
org.everit.json.schema-1.9.2.jar
paranamer-2.8.jar
re2j-1.1.jar
scala-common_2.12-0.5.64.jar
scalactic_2.12-3.0.5.jar
scala-java8-compat_2.12-0.8.0.jar
scalajs-stubs_2.12-0.6.29.jar
scala-library-2.12.6.jar
scala-reflect-2.12.8.jar
scalatest_2.12-3.0.5.jar
scala-xml_2.12-1.0.6.jar
scopt_2.12-3.7.0.jar
shacl-1.3.0.jar
slf4j-api-1.7.26.jar
slf4j-simple-1.7.12.jar
syaml_2.12-0.7.270.jar
webapi-parser-0.5.0.jar
webapi-parser-0.5.0-javadoc.jar
webapi-parser-0.5.0-sources.jar
```

```xml
<ivy-module version="2.0">
	<info organisation="mumbleMumble" module="models-ecore-raml" />
	<dependencies>
		<dependency org="org.raml" name="webapi-parser" rev="0.5.0" />
	</dependencies>
</ivy-module>
```
```xml
<ivysettings>
	<properties
		file="${ivy.settings.dir}/ivysettings-file.properties" />
	<settings defaultResolver="local-chain" />
	<resolvers>
		<ibiblio name="mulesoft-public-maven2" m2compatible="true"
			root="https://repository.mulesoft.org/nexus/content/repositories/public/" />
		<ibiblio name="mulesoft-releases-maven2"
			root="https://repository-master.mulesoft.org/nexus/content/repositories/releases"
			m2compatible="true" />
		<ibiblio name="maven"
			root="http://mvnrepository.com/artifact/" m2compatible="true" />
		<chain name="local-chain">
			<resolver ref="maven" />
			<resolver ref="mulesoft-public-maven2" />
			<resolver ref="mulesoft-releases-maven2" />
		</chain>
	</resolvers>
</ivysettings>
```

**Comment by jgsuess** [comment]
The exception is an `NPE` coming from Scala, when calling `get` on the `Future`.
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:82)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$1(FutureConvertersImpl.scala:82)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:82)
	at EndPointCreationFailsTest.test(EndPointCreationFailsTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NullPointerException
	at amf.plugins.document.webapi.resolution.stages.ExtendsResolutionStage.resourcePath(ExtendsResolutionStage.scala:196)
	at amf.plugins.document.webapi.resolution.stages.ExtendsResolutionStage.convert(ExtendsResolutionStage.scala:130)
	at amf.plugins.document.webapi.resolution.stages.ExtendsResolutionStage.transform(ExtendsResolutionStage.scala:91)
	at amf.plugins.document.webapi.resolution.stages.ExtendsResolutionStage.$anonfun$resolve$2(ExtendsResolutionStage.scala:53)
	at amf.plugins.document.webapi.resolution.stages.ExtendsResolutionStage.$anonfun$resolve$2$adapted(ExtendsResolutionStage.scala:53)
	at amf.core.model.document.BaseUnit.$anonfun$transform$2(BaseUnit.scala:105)
	at amf.core.model.document.BaseUnit.$anonfun$transform$2$adapted(BaseUnit.scala:103)
	at amf.core.model.document.BaseUnit.transformByCondition(BaseUnit.scala:144)
	at amf.core.model.document.BaseUnit.transformByCondition$(BaseUnit.scala:135)
	at amf.core.model.document.Document.transformByCondition(Document.scala:13)
	at amf.core.model.document.BaseUnit.$anonfun$transformByCondition$10(BaseUnit.scala:207)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at amf.core.model.document.BaseUnit.$anonfun$transformByCondition$7(BaseUnit.scala:199)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at amf.core.model.document.BaseUnit.transformByCondition(BaseUnit.scala:173)
	at amf.core.model.document.BaseUnit.transformByCondition$(BaseUnit.scala:135)
	at amf.core.model.document.Document.transformByCondition(Document.scala:13)
	at amf.core.model.document.BaseUnit.$anonfun$transformByCondition$7(BaseUnit.scala:181)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at amf.core.model.document.BaseUnit.transformByCondition(BaseUnit.scala:173)
	at amf.core.model.document.BaseUnit.transformByCondition$(BaseUnit.scala:135)
	at amf.core.model.document.Document.transformByCondition(Document.scala:13)
	at amf.core.model.document.BaseUnit.transform(BaseUnit.scala:112)
	at amf.core.model.document.BaseUnit.transform$(BaseUnit.scala:95)
	at amf.core.model.document.Document.transform(Document.scala:13)
	at amf.plugins.document.webapi.resolution.stages.ExtendsResolutionStage.resolve(ExtendsResolutionStage.scala:53)
	at amf.plugins.document.webapi.resolution.stages.ExtensionsResolutionStage.resolve(ExtensionsResolutionStage.scala:52)
	at amf.core.resolution.pipelines.ResolutionPipeline.step(ResolutionPipeline.scala:49)
	at amf.core.resolution.pipelines.ResolutionPipeline.$anonfun$resolve$2(ResolutionPipeline.scala:41)
	at amf.core.resolution.pipelines.ResolutionPipeline.$anonfun$resolve$2$adapted(ResolutionPipeline.scala:40)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at amf.core.resolution.pipelines.ResolutionPipeline.resolve(ResolutionPipeline.scala:40)
	at amf.plugins.document.webapi.resolution.pipelines.ValidationResolutionPipeline$.apply(ValidationResolutionPipeline.scala:35)
	at amf.plugins.document.webapi.validation.WebApiValidations.validationRequestsForBaseUnit(WebApiValidations.scala:38)
	at amf.plugins.document.webapi.validation.WebApiValidations.validationRequestsForBaseUnit$(WebApiValidations.scala:27)
	at amf.plugins.document.webapi.Raml10Plugin$.validationRequestsForBaseUnit(RamlPlugin.scala:196)
	at amf.plugins.document.webapi.BaseWebApiPlugin.validationRequest(BaseWebApiPlugin.scala:102)
	at amf.plugins.document.webapi.BaseWebApiPlugin.validationRequest$(BaseWebApiPlugin.scala:90)
	at amf.plugins.document.webapi.Raml10Plugin$.validationRequest(RamlPlugin.scala:196)
	at amf.plugins.features.validation.AMFValidatorPlugin$.modelValidation(AMFValidatorPlugin.scala:223)
	at amf.plugins.features.validation.AMFValidatorPlugin$.$anonfun$validate$1(AMFValidatorPlugin.scala:208)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by tomsfernandez** [comment]
Hi @jgsuess. Yup I agree there should be a better exception there. We will have to review the code for more cases like this one.
As our primary use case of obtaining models is by parsing a text file, over time assumptions about the fields that a certain model have crept in the code base and generate errors like yours. This doesn't happen while parsing from a text file as the absence of the "Path" field  would mean that the endpoint didn't have an identifying url segment.

I created an internal ticket: https://www.mulesoft.org/jira/browse/APIMF-3698 to keep track of this and solve it. All updates will be posted in this Github thread.

**Notes**"
- It should work if you add `endpoint.withPath(<some-value>)` to your code.
- I suggest leaving webapi-parser and instead onboarding to AMF 5.x.x which is more performant and more developer friendly than the 4.x.x line.

**Comment by jgsuess** [comment]
Yes, I had issues with validations on the 5.x line. I have a ticket for that. Is there any guidance on what the *general* conventions are? I am writing a serializer for all cases, so I would love to know what I can expect. I can run the TCK suite, but I am not sure that will cover all cases...

**Comment by jgsuess** [comment]
Also, could you please make me external listener on your ticket, so I can gauge if it is progressing or if I should give up? Without a track, this determination is difficult to make.

**Comment by tomsfernandez** [comment]
> Yes, I had issues with validations on the 5.x line. I have a ticket for that

Can you point me towards it? I don't see open issues with you as author.

> Also, could you please make me external listener on your ticket, so I can gauge if it is progressing or if I should give up?

We are working towards having open source visibility of our tickets but we don't have ir right now. Anyhow, me duplicate the Jira status in this Github ticket.

> Is there any guidance on what the general conventions are? 

We don't have a general convention of which field is present or not in the ApiContractModel. A quick WA until this issue is solved is start from an API that is similar to the one you would like or one as complete as possible and see which fields are present and which aren't. This might be useful to know which fields are expected or not.

You can also use: https://amf-model-playground.herokuapp.com/ to easily see which fields in the model are present when we parse from a text file.

**Comment by jgsuess** [comment]
Thanks for the response. The WA is appreciated. However, it does not help with my practical problem. I have parsed and analysed all classes derived from the RAML domain model, and I am attempting to build a general purpose serializer. Hence there are no structures that 'may not occur' and no 'concrete case try-outs' I can do. Basically, I have to pass the [RAML-TCK](https://github.com/raml-org/raml-tck) and produce an isomorphic result after a parse-serialize cycle to objects.

I am, based on the `with*` builder naming convention, aware of all the methods in the Domain model and can guess their respective purpose based on type. However, since the methods do not throw when used, and AML only faults after the delayed validation is called, this leaves me in the dark about causes and the state of affairs. Trial-and-error is costly.

My customer is a rather large organisation that is itself a Mulesoft customer but likes OSS to keep control. I had to advise them of the practical issues with AMF as noted in my tickets that cause project delays. I am saddened at the reception this may receive, as I believe RAML as a comprehensive solution is quite appealing.

It would be great to have this resolved. However, if I cannot get success in the week, I will close this ticket and switch the approach to OpenAPI, so you know when this is not high priority any more. I assume this will not be affecting any internal tickets you may have.

**Comment by tomsfernandez** [comment]
Hi @jgsuess. This is quite a big task as we will have to revise one by one our rendering classes in search of cases such as yours. We won't be able to solve it by this week and definitely not with a back-port to the 4.x.x if you can't upgrade to the 5.x.x line.

If it helps with something we also support Swagger 2.0, OpenApi 3.0 and AsyncApi 2.0 but the model used is the same as RAML.

**Comment by hghianni** [comment]
Hello @jgsuess this issue has been fixed and will be present in the next AMF release version 5.0.8, probably May 4. Thank you!

**Comment by jgsuess** [comment]
Thank you! This is great news. This is the release I was looking for. I think your Jedi mind tricks have worked on this release :)
