### ISSUE TITLE
JS client: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#170]
I am having following error in node version:

```
TypeError: Cannot read property 'length' of undefined
    at $c_sci_StringOps.length__I (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:167639:20)
    at $f_sc_IndexedSeqOptimized__isEmpty__Z (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:165765:17)
    at $c_sci_StringOps.isEmpty__Z (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:167550:12)
    at $f_sc_TraversableOnce__nonEmpty__Z (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:31144:18)
    at $c_Lamf_core_remote_Context$.apply__Lamf_core_remote_Platform__T__sci_Map__Lamf_core_remote_Context (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:6919:15)
    at $c_Lamf_core_remote_Context$.apply__Lamf_core_remote_Platform__T__Lamf_core_remote_Context (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:6952:43)
    at $c_Lamf_core_AMFCompiler.context$lzycompute__p1__Lamf_core_remote_Context (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:4833:78)
    at $c_Lamf_core_AMFCompiler.context__p1__Lamf_core_remote_Context (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:4820:50)
    at $c_Lamf_core_AMFCompiler.build__s_concurrent_Future (/Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:4651:14)
    at /Users/pawelpsztyc/workspace/tests/amf/node_modules/amf-client-js/amf.js:4862:239
```
I have installed nevest version of the library from npm. Any walkarounds?

**Comment by gutee** [comment]
Done in jira issue
