### ISSUE TITLE
Exception while parsing RAML files from java

### ISSUE THREAD

**Issue by petrochenko-pavel-a** [aml-org/amf#180]
Hi guys, I am parsing RAML files using Java api and observing following exception:

```raml
Caused by: java.lang.Exception: Cannot find builder for object meta amf.core.metamodel.document.ExternalFragmentModel$@37ec39ef
	at amf.core.remote.Platform.wrapFn(Platform.scala:84)
	at amf.core.remote.Platform.wrapFn$(Platform.scala:75)
	at amf.core.remote.JvmPlatform.wrapFn(JvmPlatform.scala:12)
```

According to my understanding it seems that Java wrappers for fragments are missed

Thanks in advance,
Pavel

**Comment by gutee** [comment]
This is already resolved
