### ISSUE TITLE
Loading file error in JS client

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#36]
My setup:

Node JS server side code.
Package dependency:
```
"@mulesoft/amf-js": "0.0.6-142"
```

Application code:
```
const amf = require('@mulesoft/amf-js');
const parser = new amf.RamlParser();

const url = 'http://cdn.rawgit.com/advanced-rest-client/raml-example-api/42cad8c7/api.raml';
// const url = '../../advanced-rest-client/raml-example-api/api.raml';

parser.parseFile(url, {
  success: function(doc) {
    console.log(doc);
  },

  error: function(exception) {
    console.log(exception.toString());
  }
});
```

For url defined as a local path i've got the following error:

```
java.lang.Exception: Unsupported url: ../../advanced-rest-client/raml-example-api/api.raml
```

For url with `https` scheme:

```
_http_client.js:129
    throw new Error('Protocol "' + protocol + '" not supported. ' +
    ^

Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:129:11)
    at request (http.js:39:10)
    at Object.get (http.js:43:13)
    at $c_Lamf_remote_server_JsServerPlatform.fetchHttp__T__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:16466:13)
    at $f_Lamf_remote_Platform__resolve__T__s_Option__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:1520:22)
    at $c_Lamf_remote_server_JsServerPlatform.resolve__T__s_Option__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:16421:12)
    at $c_Lamf_compiler_AMFCompiler.root__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:3294:26)
    at $c_Lamf_compiler_AMFCompiler.compile__p1__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:3190:17)
    at $c_Lamf_compiler_AMFCompiler.build__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:3180:32)
    at $c_Lamf_client_RamlParser.parseAsync__T__s_Option__s_concurrent_Future (/Users/pawelpsztyc/workspace/test/amf/node_modules/@mulesoft/amf-js/target/artifact/amf-module.js:14894:365)
```

For `http` scheme:

```
java.lang.Exception: Reference not found
```

The example RAML is the one I was using all the time working on the API console and RAML parser parses it without errors. Is there anything I can do to make it work?

**Comment by gutee** [comment]
This is no longer happening.
