### ISSUE TITLE
Domain model constructor methods produce error in JS

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#429]
With version `3.1.1` installed from npm and Node `v10.14.1` following code [1] generates proper RAML.

But when line ` .withServers([server])` is replaced with `.withServer('http://someorg.bar/{version}')` an error is produced [2] pointing to the `.withServer`. call.

This happens with all methods that receive basic types like `string` and produce instances of AMF classes. I tested it with WebApi, EndPoint, Operation, Response, Payload.

[1]
```js
// demo-amf.js
const amf = require('amf-client-js')

function main () {
  const server = new amf.model.domain.Server()
    .withUrl('http://someorg.bar/{version}')

  const api = new amf.model.domain.WebApi()
    // .withServer('http://someorg.bar/{version}')
    .withServers([server])

  const model = new amf.model.document.Document()
    .withEncodes(api)

  return amf.AMF.init()
    .then(() => {
      return amf.AMF.raml10Generator().generateString(model)
    })
    .then((generated) => {
      console.log('Generated from constructed:\n', generated)
    })
    .catch((e) => {
      console.log(e)
    })
}

return main()
```

[2]
```
/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:303
function iha(a,b){if(dc(b)){var c=(new Bs).Xm(a.uG).Ng.xr();a:{for(;c.hb();){var e=c.Va();if(e.R(b.mc())){c=(new A).c(e);break a}}c=w()}if(x(c))return a.uG.R(c.s).R(b);if(w()===c)throw ec(fc(),(new gc).f("Cannot find builder for object meta "+b.mc()));throw(new v).c(c);}if(cc(b)){c=(new Bs).Xm(a.uG).Ng.xr();a:{for(;c.hb();)if(e=c.Va(),e.R(b.mc())){c=(new A).c(e);break a}c=w()}if(x(c))return a.uG.R(c.s).R(b);if(w()===c)throw ec(fc(),(new gc).f("Cannot find builder for object meta "+b.mc()));throw(new v).c(c);
                                                                                                                                                                                   ^
Error
    at gc.d.pR (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:1714:195)
    at gc.d.ge (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:1724:187)
    at gc.f (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:2256:70)
    at iha (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:303:203)
    at Ds (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:304:233)
    at F_ (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:2373:444)
    at Tm.d.EU (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:5478:479)
    at Tm.d.AO (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:5479:30)
    at Tm.withServer (/home/someuser/projects/test-amf/node_modules/amf-client-js/amf.js:5483:159)
    at main (/home/someuser/projects/test-amf/demo-amf.js:8:6)
```

**Comment by postatum** [comment]
Looks like it's necessary to call `AMF.init()` before using these methods.
