### ISSUE TITLE
Getting integer maximum() in Java causes error

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#434]
Tested on AMF 3.1.4.
When running following code [1] an error is printed [2] even though `integer` type seems to be a whole number and not a float [according to RAML 1.0 spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#integer).

If I make it `number` and values `0.0, 125.0` everything works properly and values with digits after dots are printed.

[1]
```java
package co.acme.model;

import amf.client.AMF;
import amf.client.model.document.Document;
import amf.client.model.domain.*;

import java.util.concurrent.ExecutionException;

public class Raml10Navigation {
  public static void runExample() throws InterruptedException, ExecutionException {
    AMF.init().get();
    String ramlStr ="#%RAML 1.0\n" +
                    "types:\n" +
                    "  User:\n" +
                    "    type: object\n" +
                    "    properties:\n" +
                    "      age:\n" +
                    "        type: integer\n" +
                    "        minimum: 0\n" +
                    "        maximum: 125\n";
    Document doc = (Document) AMF.raml10Parser().parseStringAsync(ramlStr).get();
    NodeShape userType = (NodeShape) doc.declares().get(0);
    ScalarShape age = (ScalarShape) userType.properties().get(0).range();
    System.out.println("Age from " + age.minimum().value() + " to " + age.maximum().value());
  }
}
```

[2] 
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
        at scala.runtime.BoxesRunTime.unboxToDouble(BoxesRunTime.java:114)
        at amf.core.parser.Fields$DoubleFieldImpl$$anonfun$$lessinit$greater$4.apply(Fields.scala:216)
        at amf.core.parser.Fields$DoubleFieldImpl$$anonfun$$lessinit$greater$4.apply(Fields.scala:216)
        at scala.Option.map(Option.scala:146)
        at amf.core.parser.Fields$DoubleFieldImpl.<init>(Fields.scala:216)
        at amf.core.parser.Fields.typed$1(Fields.scala:38)
        at amf.core.parser.Fields.$anonfun$field$2(Fields.scala:66)
        at scala.Option.map(Option.scala:146)
        at amf.core.parser.Fields.field(Fields.scala:66)
        at amf.plugins.domain.shapes.models.CommonShapeFields.minimum(CommonShapeFields.scala:12)
        at amf.plugins.domain.shapes.models.CommonShapeFields.minimum$(CommonShapeFields.scala:12)
        at amf.plugins.domain.shapes.models.ScalarShape.minimum(ScalarShape.scala:14)
        at amf.client.model.domain.ScalarShape.minimum(ScalarShape.scala:19)
        at co.acme.model.Raml10Navigation.runExample(Raml10Navigation.java:24)
        at co.acme.demo.AmfDemo.main(AmfDemo.java:54)
```

**Comment by gutee** [comment]
This is no longer happening
