### ISSUE TITLE
Type expression using type "file" produces an error when generating amf graph

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#540]
True for both amf-client-js 3.2.2 and 3.3.0.

Running code [1] produces and error [2]. Changing RAML type definition to [3] fixes the issue.
The error is caused by the line `const graph...` .

[1]
```js
const amf = require('amf-client-js')

const ramlStr = `
#%RAML 1.0 Library
types:
  Photo: file
`

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseStringAsync(ramlStr)
  const graph = await amf.AMF.amfGraphGenerator().generateString(model)
  console.log(graph)
}

main()
```
[2]
```sh
$ node raml10.js 
(node:13245) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of null
    at Jf (/projects/amf-js-test/node_modules/amf-client-js/amf.js:1100:29)
    at UDa (/projects/amf-js-test/node_modules/amf-client-js/amf.js:1329:109)
    at /projects/amf-js-test/node_modules/amf-client-js/amf.js:1330:385
    at u.R (/projects/amf-js-test/node_modules/amf-client-js/amf.js:2468:216)
    at hda (/projects/amf-js-test/node_modules/amf-client-js/amf.js:121:264)
    at wX.d.Nq (/projects/amf-js-test/node_modules/amf-client-js/amf.js:2299:264)
    at tEa (/projects/amf-js-test/node_modules/amf-client-js/amf.js:1330:339)
    at fEa (/projects/amf-js-test/node_modules/amf-client-js/amf.js:1328:275)
    at /projects/amf-js-test/node_modules/amf-client-js/amf.js:1334:55
    at u.R (/projects/amf-js-test/node_modules/amf-client-js/amf.js:2468:216)
(node:13245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
[3]
```raml
#%RAML 1.0 Library
types:
  Photo:
    type: file
```

**Comment by gutee** [comment]
Tracking this internally as https://www.mulesoft.org/jira/browse/APIMF-1599

**Comment by gutee** [comment]
This is fixed for the next version of amf
