### ISSUE TITLE
Parse RAML from network directory

### ISSUE THREAD

**Issue by dsimpsonOMF** [aml-org/amf#560]
I am trying to use this library from within the raml-org's wrapper in java, but it seems it can't access that directory. See error below:

`Exception in thread "main" java.util.concurrent.ExecutionException: amf.core.remote.FileNotFound: File Not Found: S:\...\credit-applications-sapi.raml (The system cannot find the path specified)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:82)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$1(FutureConvertersImpl.scala:82)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:82)
	at fin.corp.es.coe.mulesoft.report.ramlreview.RamlChecker2.checkProject(RamlChecker2.java:94)
	at fin.corp.es.coe.mulesoft.report.ramlreview.RamlChecker2.main(RamlChecker2.java:43)
Caused by: amf.core.remote.FileNotFound: File Not Found: S:\...\credit-applications-sapi.raml (The system cannot find the path specified)
	at amf.client.resource.FileResourceLoader.$anonfun$fetchFile$1(FileResourceLoader.scala:31)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.FileNotFoundException: S:\...\credit-applications-sapi.raml (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at amf.core.lexer.CharArraySequence$.apply(CharArraySequence.scala:29)
	at amf.core.lexer.FileStream.<init>(FileStream.scala:8)
	at amf.core.lexer.FileStream.<init>(FileStream.scala:11)
	at amf.client.resource.FileResourceLoader.$anonfun$fetchFile$1(FileResourceLoader.scala:27)
	... 12 more`

And of course I copied the location out of the error and was able to use it directly, therefore I know the path is valid.

**Comment by postatum** [comment]
@dsimpsonOMF Hi. Try prefixing file path with `file:///`.

**Comment by dsimpsonOMF** [comment]
I have an instance of the java.io.File.File class which I call .toURI().toString() on. This comes prefixed with "file:/" on the beginning of the path when I pass it in as an arg. I am sorry that I didn't put that in the original post. Point still stands however that it can't find that file.

**Comment by gutee** [comment]
Hi, this is a Windows path right? Meaning that you use AMF with any of the parse file methods passing this parameter 'file:///S:/some-path/credit-applications-sapi.raml'?
